robot_localization_node:
  ros__parameters:
    map_frame: map
    odom_frame: odom
    base_frame: base_footprint
    voxel_filter_size: 0.025
    origin:
      x: -0.5
      y: -1.5
      theta: 0.
      init:
        global_init: false
        radius: 2.0
        branch_and_bound_depth: 8
    update:
      nomotion_update: true
      min_d_update: 0.05
      min_a_update: 0.2
    fast_scan_matcher:
      linear_search_window: 1.0
      angular_search_window: 3.14
      branch_and_bound_depth: 8
    realtime_scan_matcher:
      linear_search_window: 0.1
      angular_search_window: 0.4
      translation_delta_cost_weight: 0.1
      rotation_delta_cost_weight: 0.1
    ceres_scan_matcher:
      occupied_space_weight: 1.
      translation_weight: 1.
      rotation_weight: 1.
      linear_search_window: 0.05
      angular_search_window: 0.2
      ceres_solver_options:
        use_nonmonotonic_steps: false
        max_num_iterations: 5
        num_threads: 1
    point_cloud_insertor:
      update_map: false
      map_update_interval: 0.5 #hz
      hit_probability: 0.8
      miss_probability: 0.49
    adaptive_voxel_filter:
      max_length: 0.9
      min_num_points: 100
      max_range: 15.
      min_range: 0.1